blog/urls.py
from django.conf.urls import url

from .views import CategoryListView, CreateCategoryView, ArticleListView, ArticleCreateView, ArticleDetail, ArticleEditView, ArticleDeleteView

urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name='article_category_list'),
    url(r'^create_category/$', CreateCategoryView.as_view(), name='category_create'),
    url(r'^(?P<category_slug>[\w-]+)/$', ArticleListView.as_view(), name='article_list'),
    url(r'^(?P<category_slug>[\w-]+)/create/$', ArticleCreateView.as_view(), name='article_create'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$', ArticleDetail.as_view(), name='article_detail'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/edit$', ArticleEditView.as_view(), name='article_edit'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/delete$', ArticleDeleteView.as_view(), name='article_delete'),
]

homepage/urls.py
from django.conf.urls import url
from homepage.views import index, about_edit, contacts_edit, NewTileView, DeleteTileView
from django.contrib.flatpages.views import flatpage


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^new_tile/$', NewTileView.as_view(), name='new_tile'),
    url(r'^tile-delete/$', DeleteTileView.as_view(), name='delete_tile'),
    url(r'^about/$', flatpage, {'url': '/about/'}, name='about'),
    url(r'^about/edit$', about_edit, name='about_edit'),
    url(r'^contacts/$', flatpage, {'url': '/contacts/'}, name='contacts'),
    url(r'^contacts/edit$', contacts_edit, name='contacts_edit'),
]

homepage/models.py
from django.db import models
from PIL import Image
from shop.models import Service, Product


class ServiceTile(models.Model):
    pages = models.OneToOneField(Service, null=True)

    def __str__(self):
        return "Страницы для отображения на главной (плитки)"

    class Meta:
        verbose_name = "Плитка на главной странице"
        verbose_name_plural = "Плитки на главной странице"


class ProductTile(models.Model):
    pages = models.OneToOneField(Product, null=True)

    def __str__(self):
        return "Страницы для отображения на главной (плитки)"

    class Meta:
        verbose_name = "Плитка на главной странице"
        verbose_name_plural = "Плитки на главной странице"


class MainSetting(models.Model):
    firm_name = models.CharField('Название компании', max_length=70)
    phone1 = models.CharField('Номер телефона', max_length=20)
    phone2 = models.CharField('Номер телефона', max_length=20, blank=True)
    address = models.TextField('Адрес', max_length=500,)
    work_time = models.TextField('Время работы', max_length=500)
    logo = models.ImageField('Логотип', upload_to='homepage')
    favicon = models.ImageField('Маленькая иконка сайта во вкладке', upload_to='homepage', blank=True)
    active = models.BooleanField('Настройки активны', default=False, help_text='Только одна запись должна быть активна')

    class Meta:
        unique_together = ("active",)
        verbose_name = "Главные настройки"
        verbose_name_plural = "Главные настройки"

    def __str__(self):
        return "Главные настройки сайта. Информация в верхней части"

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from ckeditor_uploader.fields import RichTextUploadingField

from blog.models import Article
from shop.managers import ProductManager


class Manufacturer(models.Model):
    title = models.CharField('Название', max_length=100)
    slug = models.SlugField('Генерируется автоматически', unique=True, null=True, blank=True)

    def get_request_part(self):
        return "manufacturer=%s&" % self.slug

    def get_absolute_url(self):
        url = reverse("filtered_product_list")
        return url + "?" + self.get_request_part()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'


class ProductGroup(models.Model):
    title = models.CharField('Название группы товаров', max_length=500)
    image = models.ImageField(verbose_name="Изображение", null=True, blank=True)
    slug = models.SlugField('Генерируется автоматически', unique=True, null=True, blank=True)

    meta_description = models.CharField('SEO Описание', max_length=2000, blank=True, null=True)
    meta_title = models.CharField(verbose_name="SEO заголовок", max_length=500, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_all_categories(self):
        products = self.product_set.active()
        qs = Category.objects.filter(product__in=products).distinct()
        return qs

    def get_all_manufacturers(self):
        products = self.product_set.active()
        qs = Manufacturer.objects.filter(product__in=products).distinct()
        return qs

    def get_request_part(self):
        return "group=%s&" % self.slug

    class Meta:
        verbose_name = "Группа товаров"
        verbose_name_plural = "Группы товаров"


class Currency(models.Model):
    title = models.CharField('Валюта', max_length=100)
    rate = models.FloatField()

    def __str__(self):
        return self.title

    def convert_to_curr(self, cur):
        return self.rate/Currency.objects.get(title=cur).rate

    class Meta:
        verbose_name = "Курс валюты"
        verbose_name_plural = "Курсы валют"


class Category(models.Model):
    title = models.CharField('Название категории', max_length=500, unique=True)
    description = RichTextUploadingField('Описание', max_length=5000)
    slug = models.SlugField('Генерируется автоматически', unique=True, null=True, blank=True)
    image = models.ImageField(upload_to='category_image', null=True, blank=True)

    meta_description = models.CharField('SEO Описание', max_length=2000, blank=True, null=True)
    meta_title = models.CharField(verbose_name="SEO заголовок", max_length=500, blank=True, null=True)

    def get_request_part(self):
        return "category=%s&" % self.slug

    def get_absolute_url(self):
        url = reverse("filtered_product_list")
        return url + "?" + self.get_request_part()

    def get_absolute_url_for_blog(self):
        return reverse("article_list", args=[str(self.slug)])

    def get_absolute_url_for_service(self):
        return reverse("service_list", args=[str(self.slug)])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    title = models.CharField('Название', max_length=200)
    avatar = models.ImageField('Изображение', upload_to='items_avatars')
    text_preview = RichTextUploadingField('Краткое описание', max_length=5000, null=True, blank=True)

    price = models.FloatField('Цена', blank=True, null=True)
    new_price = models.FloatField("Цена со скидкой", blank=True, null=True)
    currency = models.ForeignKey(Currency, verbose_name='Валюта')

    description = RichTextUploadingField('Описание', max_length=10000)
    available = models.BooleanField(verbose_name="Доступ", default=True)

    category = models.ManyToManyField(Category, verbose_name="Категория")
    relation = models.ManyToManyField('self', blank=True, symmetrical=True)

    manufacturer = models.ForeignKey(Manufacturer, verbose_name='Производитель')
    group = models.ForeignKey(ProductGroup, verbose_name="Группа товаров")

    # Manager
    objects = ProductManager()

    def get_absolute_url(self):
        return reverse("product_detail", args=[str(self.id)])

    def get_category_slug(self):
        return self.category.first().slug

    def get_price_ruble(self):
        return self.price * self.currency.convert_to_curr('RUB')

    def get_price_usd(self):
        return self.price * self.currency.convert_to_curr('USD')

    def get_price_eur(self):
        return self.price * self.currency.convert_to_curr('EUR')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class Service(models.Model):
    class Meta:
        verbose_name_plural = "Услуги"
        verbose_name = "Услуга"

    title = models.CharField(verbose_name="Название", max_length=500)
    description = RichTextUploadingField('Описание', max_length=10000)

    text_preview = models.CharField(verbose_name='Краткое описание', max_length=1000, null=True, blank=True)

    meta_title = models.CharField(verbose_name="SEO заголовок", max_length=500)
    meta_description = models.CharField(verbose_name="SEO описание", max_length=5000)

    image = models.ImageField(verbose_name="Изображение")

    price = models.FloatField(verbose_name="Цена", blank=True, null=True)
    new_price = models.FloatField(verbose_name="Цена со скидкой", blank=True, null=True)

    available = models.BooleanField(verbose_name="Доступ", default=True)

    currency = models.ForeignKey(Currency, blank=True, null=True)

    group = models.ForeignKey(ProductGroup, blank=True, null=True)

    def get_absolute_url(self):
        return reverse("service_detail", args=[str(self.pk)])

    def __str__(self):
        return str(self.title)

homepage/forms.py
from django import forms
from django.contrib.flatpages.models import FlatPage
from .models import ProductTile, ServiceTile
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class AboutForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget(config_name='awesome_ckeditor'))

    class Meta:
        model = FlatPage
        fields = [
            'title',
            'content'
        ]


class ContactForm(forms.ModelForm):
    class Meta:
        model = FlatPage
        fields = [
            'title',
            'content',
        ]
        widgets = {
            'title': CKEditorUploadingWidget(config_name='awesome_ckeditor'),
            'content': CKEditorUploadingWidget(config_name='awesome_ckeditor'),
        }


class ServiceTileForm(forms.ModelForm):

    class Meta:
        model = ServiceTile
        fields = ('pages',)


class ProductTileForm(forms.ModelForm):
    class Meta:
        model = ProductTile
        fields = ('pages',)

homepage/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.flatpages.models import FlatPage
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, DeleteView
from django.utils.decorators import method_decorator

from .models import ServiceTile
from blog.models import Article
from .forms import AboutForm, ContactForm, ServiceTileForm


def index(request):
    tiles = ServiceTile.objects.all()
    articles = Article.objects.all().order_by('-published')[:3]
    form = ServiceTileForm
    services = [tile.pages for tile in tiles]
    can_add = len(services) < 6 and (request.user.is_staff or request.user.is_superuser)

    return render(request, 'homepage/index.html', {'services': services, 'form': form, "articles": articles, 'canAdd': can_add})


@method_decorator(login_required(), name="dispatch")
class NewTileView(CreateView):
    model = ServiceTile
    form_class = ServiceTileForm
    success_url = '/'

    def form_invalid(self, form):
        return HttpResponse("Плитка со ссылкой на эту услугу уже создана <a href=\"/\">Вернуться на главую </a>")


@method_decorator(login_required(), name="dispatch")
class DeleteTileView(DeleteView):
    model = ServiceTile
    form_class = ServiceTileForm
    success_url = '/'

    def get_object(self, queryset=None):
        id_tile_to_delete = int(self.request.POST.get('id-to-delete'))
        tile = ServiceTile.objects.get(pages__pk=id_tile_to_delete)
        return tile


def about_edit(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(FlatPage, url='/about/')    
    form = AboutForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect("about")

    context = {
        'instance': instance,
        'form': form,
    }
    return render(request, "homepage/FlatPagesForm.html", context)


def contacts_edit(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(FlatPage, url='/contacts/')    
    form = ContactForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect("contacts")

    context = {
        'instance': instance,
        'form': form,
    }
    return render(request, "homepage/FlatPagesForm.html", context)

homepage/templates/homepage/FlatPagesForm.html
{% extends "homepage/base.html" %}
{% load staticfiles %}
{% block content %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Форма для заполнения</h1>
    <form action="" method="POST" enctype="multipart/form-data" class="article-form">  {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="save btn btn-default">Сохранить</button>
    </form>
  </div>
</div>
{% endblock content %}

homepage/templates/homepage/about.html
{% extends "homepage/base.html" %}
{% load staticfiles %}

{% block content %}

    <div class="position-relative" style="max-width: 100%; overflow: hidden">
        <div class="row">
            {% if request.user.is_staff or request.user.is_superuser %}
                <a href="{% url 'about_edit' %}" style="position: absolute; color: red; right:40px;">Редактировать</a>
            {% endif %}

            <div class="col-xs-12">
                {{ flatpage.content }}
            </div>
        </div>

    </div>


{% endblock content %}

homepage/templates/homepage/base.html
{% load staticfiles %}
{% load page_extras %}
<!--DOCTYPE html-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="/media/homepage/favicon.ico" type="image/x-icon">
    <title>
        {% block head_title %}
        {% endblock head_title %}
    </title>
    <!-- Bootstrap -->
    <link href="{% static 'homepage/css/bootstrap-flex.min.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/fonts/fonts.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head_extra %}
    {% endblock head_extra %}

</head>
<body>
<script src="{% static 'homepage/js/jquery-3.1.1.min.js' %}"></script>

<header>
    <!-- Header start -->
    {% show_top %}
    <!--  Header end -->

    {% show_menu request.path %}
</header>

<main>
 <div class="for-back-img"></div>
    {% block content %}
    {% endblock content %}
</main>

<footer>
{% include "homepage/footer.html" %}
</footer>

<!-- jQuery first, then Tether, then Bootstrap JS. -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js"
        integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8"
        crossorigin="anonymous"></script>
<script src="{% static 'homepage/js/bootstrap.min.js' %} "></script>

<script type="text/javascript"
        src="{% static 'homepage/js/jquery-validation-1.16.0.js/dist/jquery.validate.min.js' %}"></script>
<script type="text/javascript"
        src="{% static 'homepage/js/jquery-validation-1.16.0.js/dist/localization/messages_ru.min.js' %}"></script>


{% block extra_script %}
{% endblock extra_script %}
</body>
</html>

homepage/templates/homepage/contacts.html
{% extends "homepage/base.html" %}
{% load staticfiles %}


{% block content %}

    <div class="position-relative" style="max-width: 100%; overflow: hidden">
        <div class="row" >
            {% if request.user.is_staff or request.user.is_superuser %}
                <a href="{% url 'contacts_edit' %}" style="position: absolute; color: red;">Редактировать</a>
            {% endif %}

            <div class="col-xs-12">
                <div class="double-gis">
                    <a class="dg-widget-link" href="http://2gis.ru/novosibirsk/firm/70000001023599875/center/82.89321899414064,54.99477638901002/zoom/15?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=bigMap">Посмотреть на карте Новосибирска</a><div class="dg-widget-link"><a href="http://2gis.ru/novosibirsk/center/82.892311,54.993614/zoom/15/routeTab/rsType/bus/to/82.892311,54.993614╎ТехВентСервис, ООО, сервисный центр?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=route">Найти проезд до ТехВентСервис, ООО, сервисный центр</a></div><script charset="utf-8" src="https://widgets.2gis.com/js/DGWidgetLoader.js"></script><script charset="utf-8">new DGWidgetLoader({"width":"100%","height":600,"borderColor":"#a3a3a3","pos":{"lat":54.99477638901002,"lon":82.89321899414064,"zoom":15},"opt":{"city":"novosibirsk"},"org":[{"id":"70000001023599875"}]});</script><noscript style="color:#c00;font-size:16px;font-weight:bold;">Виджет карты использует JavaScript. Включите его в настройках вашего браузера.</noscript>
                </div>
            </div>
            <div class="col-xs-12">
                <h1>{{ flatpage.title }}</h1>
                {{ flatpage.content }}
            </div>
        </div>

    </div>

{% endblock content %}

homepage/templates/homepage/footer.html
<div style="background-color: #9db4b7; padding: 5px;">
    <small>ТехВентСервис 2017</small>
</div>

homepage/templates/homepage/index.html
{% extends "homepage/base.html" %}
{% load staticfiles %}

{% block head_title %}Главная страница{% endblock head_title %}

{% block content %}
    <div class="homepage-content container-fluid">
        <div class="row service-list">
            {% for service in services %}
                <div class="col-md-4 col-sm-6">
                    <div class="card service-list-item">
                        <a href="{{ service.get_absolute_url }}">
                            <div class="service-list-item-image">
                                <img class="card-img-top img-fluid" src="/media/{{ service.image }}" alt="Card image cap">
                            </div>
                            <div class="card-block">
                                <h5 class="card-text">{{ service.title|truncatechars:100 }}</h5>
                            </div>
                        </a>
                        {% if user.is_staff or user.is_superuser %}
                            <form method="post" action="/tile-delete/"> {% csrf_token %}
                                <input type="hidden" class="number-tile-delete" value="{{ service.pk }}"
                                       name="id-to-delete">
                                <button class="btn btn-danger btn-tile-delete">x</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            {% if canAdd %}
                <div class="col-md-4 col-sm-12" style="text-align: center">
                    <span id="new-tile">
                        +
                    </span>
                    <div id="div-new-tile"></div>
                </div>
            {% endif %}
        </div>
        <hr>
        <div class="row">
            <a href='{% url 'product_list' %}' class="btn btn-primary" style="z-index: 2;">Перейти в магазин</a>
        </div>

        {% if articles %}
            <hr>
            <div class="row">
                {% for article in articles %}
                    <div class="col-sm-6">
                        <div class="homepage__article">
                            <h3><a href={{ article.get_absolute_url }}>{{ article.title }}</a></h3>
                            <p>{{ article.get_markdown|safe|truncatechars_html:500 }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

{% block extra_script %}
<script>
        $("#new-tile").click(function () {
        $("#div-new-tile").html("<form method=\"POST\" action=\" /new_tile/ \" > {% csrf_token %} {{ form.as_p | escapejs}} <button id=\"add-tile\" class=\"save btn btn-default\">Добавить</button></form>");
    });
    $(document).ready(function () {
        $("#new-tile").fadeTo('fast', 0.5)
            .mouseenter(function () {
                $(this).fadeTo('fast', 1);
            })
            .mouseleave(function () {
                $(this).fadeTo('fast', 0.5);
            });
    });
</script>
{% endblock extra_script %}

homepage/templates/homepage/index2.html
{% load staticfiles %}
{% load page_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="/media/homepage/favicon.ico" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>
    {% block head_title %}
    {% endblock head_title %}
    </title>
    <!-- Bootstrap -->
    <link href="{% static 'homepage/css/bootstrap-flex.min.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/fonts/fonts.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head_extra %}
    {% endblock head_extra %}
<!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="{% static 'homepage/js/jquery-3.1.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
    <script src="{% static 'homepage/js/bootstrap.min.js'%} "></script>

  </head>
  <body>


<div class="container-fluid"> 

<!-- Header start -->
    {% show_top %}
<!--  Header end -->

    {% show_menu request.path %}

<h1 class="main"></h1>
</div>



    <script type="text/javascript">
            $(document).ready(function() {
                // using jQuery
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');
                function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
                var ans = $.post('/test_ajax/',{name: 'Artem Zverev'},function(){alert("Успех");},"json")
                        .done(function () {
                            alert('eee'+ ans);
                            $('.main').html('zhopa'+ans[name]);
                        })
                        .fail(function () {
                            alert('fail'); })
                        .always(function () {
                            alert('always');
                        });
                        });
    </script>

  </body>
</html>

homepage/templates/homepage/menu.html
{% load page_extras %}
<div class="container-fluid">
    <div class="row menu-row hidden-sm-down">
        <nav class="main-menu ">
            <ul class="nav nav-justified main-menu-ul">
                {% if '/' == path %}
                    <li class="active main-menu-li"><a class="main-menu-li-a" href="/">Главная</a></li>
                {% else %}
                    <li class="main-menu-li"><a class="main-menu-li-a" href="/">Главная</a></li>
                {% endif %}


                {% if '/market/shop/' in path %}
                    <li class="active main-menu-li"><a class="main-menu-li-a" href="/market/shop/">Товары</a></li>
                {% else %}
                    <li class="main-menu-li"><a class="main-menu-li-a" href="/market/shop/">Товары</a></li>
                {% endif %}


                {% if '/market/service/' in path %}
                    <li class="active main-menu-li"><a class="main-menu-li-a" href="/market/service/">Услуги</a></li>
                {% else %}
                    <li class="main-menu-li"><a class="main-menu-li-a" href="/market/service/">Услуги</a></li>
                {% endif %}


                {% if '/article/' in path %}
                    <li class="active main-menu-li"><a class="main-menu-li-a" href="/article/">Статьи</a></li>
                {% else %}
                    <li class="main-menu-li"><a class="main-menu-li-a" href="/article/">Статьи</a></li>
                {% endif %}


                {% if '/about/' in path %}
                    <li class="active main-menu-li"><a class="main-menu-li-a" href="/about/">О нас</a></li>
                {% else %}
                    <li class="main-menu-li"><a class="main-menu-li-a" href="/about/">О нас</a></li>
                {% endif %}


                {% if '/contacts/' in path %}
                    <li class="active main-menu-li"><a class="main-menu-li-a" href="/contacts/">Контакты</a></li>
                {% else %}
                    <li class="main-menu-li"><a class="main-menu-li-a" href="/contacts/">Контакты</a></li>
                {% endif %}

                {% if user.is_superuser or user.is_staff %}
                    {% if path == '/orders/' %}
                        <li class="active main-menu-li"><a class="main-menu-li-a" href="/orders/">Заказы</a></li>
                    {% else %}
                        <li class="main-menu-li"><a class="main-menu-li-a" href="/orders/">Заказы</a></li>
                    {% endif %}
                {% endif %}

                <!-- {% for page in menu_pages %}
        {% if page.get_absolute_url == path  %}
            <li class="active"><a href="{{ page.get_absolute_url }}">{{ page.title }}</a></li>
        {% else %}
            <li><a href="{{ page.get_absolute_url }}">{{ page.title }}</a></li>
        {% endif %}
    {% empty %}
        <li> Нет страниц в меню</li>
    {% endfor %} -->

            </ul>
        </nav>
    </div>
</div>

<div class="dropdown">
    <button class="btn btn-block btn-primary dropdown-toggle hidden-md-up" type="button" data-toggle="dropdown">Меню
        <span class="caret"></span></button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="/">Главная</a></li>
        <div class="dropdown-divider"></div>
        <li><a class="dropdown-item" href="/market/shop/">Магазин</a></li>
        <div class="dropdown-divider"></div>
        <li><a class="dropdown-item" href="/market/service/">Услуги</a></li>
        <div class="dropdown-divider"></div>
        <li><a class="dropdown-item" href="/article/">Статьи</a></li>
        <div class="dropdown-divider"></div>
        <li><a class="dropdown-item" href="/about/">Статьи</a></li>
        <div class="dropdown-divider"></div>
        <li><a class="dropdown-item" href="/contacts/">Контакты</a></li>
        {% if user.is_superuser or user.is_staff %}
            <div class="dropdown-divider"></div>
            <li><a class="dropdown-item" href="/orders/">Заказы</a></li>
        {% endif %}
    </ul>
</div>
<!-- <a id="touch-menu" class="mobile-menu hidden-md-up " href="#"><i class="icon-reorder"></i>Menu</a> -->